<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'bookss' => [[], ['_controller' => 'App\\Controller\\BookController::modal'], [], [['text', '/book']], [], [], []],
    'app.home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'auth.login' => [[], ['_controller' => 'App\\Controller\\HomeController::login'], [], [['text', '/login']], [], [], []],
    'auth.register' => [[], ['_controller' => 'App\\Controller\\HomeController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\BookController::modal' => [[], ['_controller' => 'App\\Controller\\BookController::modal'], [], [['text', '/book']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\HomeController::login' => [[], ['_controller' => 'App\\Controller\\HomeController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\HomeController::register' => [[], ['_controller' => 'App\\Controller\\HomeController::register'], [], [['text', '/register']], [], [], []],
];
